services:
  blocky:
    image: ghcr.io/0xerr0r/blocky:v0.24@sha256:9a82e0235c52ef3048586f8006add06e52132adaae70d02f980569dae16421a2
    container_name: blocky
    network_mode: bridge
    environment:
      - TZ=America/Edmonton
    volumes:
      - ./data/config/config.yaml:/app/config.yml:ro
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    labels:
      - traefik.enable=true
      - traefik.http.routers.blocky.rule=Host(`blocky.jory.casa`)
      - traefik.http.routers.blocky.entrypoints=web
      - traefik.http.services.blocky.loadbalancer.server.port=4000
    restart: unless-stopped
