services:
  bws-cache:
    image: ghcr.io/ripplefcl/bws-cache:v1.1.0@sha256:bcee868971c14cf9180249059c386706b8ab2ad3f3749762006aa261f6490744
    container_name: bws-cache
    network_mode: bridge
    env_file:
    - path: ./data/config/config.sops.env
    ports:
      - '5000:5000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.bws-cache.rule=Host(`bws-cache.jory.casa`)
      - traefik.http.routers.bws-cache.entrypoints=web
      - traefik.http.services.bws-cache.loadbalancer.server.port=5000
    restart: unless-stopped
