services:
  traefik:
    image: docker.io/library/traefik:v3.0.0
    container_name: traefik
    network_mode: bridge
    env_file:
      ./data/config/config.sops.env
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - ./data/cache:/data
      - ./data/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
