services:
  bind:
    image: docker.io/ubuntu/bind9:9.18-22.04_beta
    container_name: bind
    restart: unless-stopped
    user: "0" # root
    environment:
      - TZ=America/Edmonton
      - BIND9_USER=root
    volumes:
      - ./bind/data/cache:/var/cache/bind
      - ./bind/data/config:/etc/bind:ro
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "5301:5301/tcp"
      - "5301:5301/udp"

  blocky:
    image: ghcr.io/0xerr0r/blocky:v0.23
    container_name: blocky
    restart: unless-stopped
    environment:
      - TZ=America/Edmonton
    volumes:
      - ./blocky/data/config/config.yaml:/app/config.yml:ro
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      - traefik.enable=true
      - traefik.http.routers.blocky.rule=Host'(`blocky.jory.casa`)'
      - traefik.http.routers.blocky.entrypoints="web"
      - traefik.http.services.blocky.loadbalancer.server.port="4000"
