---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  bootstrap:
    desc: Copy NUT config files
    cmds:
      - sudo apt install -y nut nut-client nut-server
      - sudo rsync -rv --delete {{.ROOT_DIR}}/nut/ups/ /etc/nut/
      - sudo sed -i "s/pass_placeholder/$(cat {{.ROOT_DIR}}/nut/ups/password.secret | sed 's/\//\\\//g')/" /etc/ups/* | bash
      - sudo service nut-server restart
      - sudo service nut-client restart
      - sudo systemctl restart nut-monitor
      - sudo upsdrvctl stop
      - sudo upsdrvctl start
