services:
  bind:
    image: docker.io/ubuntu/bind9:9.18-22.04_beta@sha256:1dc6d428e149fcba4a43894e15f229c65c34180ab7c7010e94667ea46877f5ea
    container_name: bind
    network_mode: bridge
    user: "0" # root
    environment:
      - TZ=America/Edmonton
      - BIND9_USER=root
    volumes:
      - ./bind/data/cache:/var/cache/bind
      - ./bind/data/config:/etc/bind:ro
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "5301:5301/tcp"
      - "5301:5301/udp"
    restart: unless-stopped

  blocky:
    image: ghcr.io/0xerr0r/blocky:v0.23@sha256:450d193393c0dceb108d1cd80a5580ab9d851127c924c1ae89361d32161ae528
    container_name: blocky
    network_mode: bridge
    environment:
      - TZ=America/Edmonton
    volumes:
      - ./blocky/data/config/config.yaml:/app/config.yml:ro
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    restart: unless-stopped
